fun main(){
    print("Enter student name: ")
    val name = readLine()
    print("Enter enrolment number: ")
    val enrolmentNo = readLine()
    print("Enter branch: ")
    val branch = readLine()
    print("Enter Class : ")
    var clas = readLine()
    print("Enter Batch : ")
    var batch =readLine()
    print("Enter College : ")
    var Cllg = readLine()
    print("Enter University : ")
    var uni = readLine()
    print("Enter Age : ")
    var age = readLine()
    println("Information Status :")
    println("Name: $name")
    println("Enrolment No: $enrolmentNo")
    println("Branch: $branch ")
    println("Class: $clas ")
    println("Batch: $batch")
    println("College: $Cllg")
    println("University: $uni ")
    println("Age: $age")
}
